# Generated by Django 4.2.6 on 2023-10-05 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infoAPI', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdb',
            name='phno',
            field=models.CharField(default='09260000000', max_length=11),
        ),
    ]
